'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ExamenFinalWeb

    Partial Public Class Contactos
        Public Property id_contacto As Integer
        Public Property nombre As String
        Public Property apellido As String
        Public Property cedula As String
        Public Property fecha_creacion As Nullable(Of Date)
    
    End Class

End Namespace
