'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace ExamenFinalWeb

    Partial Public Class Motivodevisita
        Public Property id_visita As Integer
        Public Property fecha_visita As Nullable(Of Date)
        Public Property hora_entrada As Nullable(Of System.TimeSpan)
        Public Property hora_salida As Nullable(Of System.TimeSpan)
        Public Property nombrecompleto As String
        Public Property Contactoquerecibio As String
    
    End Class

End Namespace
